# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0
  cypress: cypress-io/cypress@2
  snyk: snyk/snyk@1.2.3
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
  jq: circleci/jq@2.2.0
  sonarcloud: sonarsource/sonarcloud@1.0.3
executors:
  with-chrome:
    resource_class: large
    docker:
      - image: 'cypress/browsers:node16.14.2-slim-chrome100-ff99-edge'

jobs:
  build_production:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - aws-s3/copy:
          from: build/
          to: s3://techscrumapp.com
          arguments: --recursive
      - aws-cloudfront/invalidate:
          distribution_id: E28E7CS1KHPD0K
          paths: /*
  build_staging:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - aws-s3/copy:
          from: build/
          to: s3://staging.techscrumapp.com
          arguments: --recursive
      - aws-cloudfront/invalidate:
          distribution_id: E28E7CS1KHPD0K
          paths: /*
  build_dev:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - aws-s3/copy:
          from: build/
          to: s3://dev.techscrumapp.com
          arguments: --recursive
      - aws-cloudfront/invalidate:
          distribution_id: E28E7CS1KHPD0K
          paths: /*
  security_check:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      # - snyk/scan
  code_qa:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - sonarcloud/scan

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - jq/install
      - run: yarn lint
  bump_patch:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - run: echo 'WIP'
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  simple_workflow:
    jobs:
      - security_check
      - code_qa
      - cypress/install:
          yarn: true
          executor: with-chrome
      - cypress/run:
          requires:
            - cypress/install
          wait-on: 'http://localhost:3000'
          yarn: true
          executor: with-chrome
          browser: chrome
          start: yarn start
          record: true
      - build_production:
          requires:
            - code_qa
            - security_check
          filters:
            branches:
              only:
                - master
      - build_staging:
          requires:
            - code_qa
            - security_check
          filters:
            branches:
              only:
                - staging
      - build_dev:
          requires:
            - code_qa
            - security_check
            - cypress/run
          filters:
            branches:
              only:
                - develop
      - bump_patch:
          requires:
            - build_dev
          filters:
            branches:
              only:
                - develop